netty.default.allocator.max-order = 3
elasticsearch.httpHosts = 'http://localhost:9200,http://127.0.0.2:9200'
nats.addresses = ['nats://localhost:4222']

[micronaut]
application.name = 'demoapp'
caches.my-cache.maximumSize = 20

[datasources.default]
url = 'jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE'
driverClassName = 'org.h2.Driver'
username = 'sa'
password = ''
schema-generate = 'CREATE_DROP'
dialect = 'H2'

[micronaut.security]
authentication = 'session'
token.jwt.signatures.secret.generator.secret = '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
intercept-url-map = [{access = 'isAnonymous()', pattern = '/swagger/**'}, {access = 'isAnonymous()', pattern = '/swagger-ui/**'}]

[micronaut.router.static-resources.swagger]
paths = 'classpath:META-INF/swagger'
mapping = '/swagger/**'

[micronaut.router.static-resources.swagger-ui]
paths = 'classpath:META-INF/swagger/views/swagger-ui'
mapping = '/swagger-ui/**'

[micronaut.security.oauth2.clients.default]
client-id = '${OAUTH_CLIENT_ID}'
client-secret = '${OAUTH_CLIENT_SECRET}'
openid.issuer = '${OAUTH_ISSUER}'
